name: Build action

on: push

jobs:
  build:
    name: Build unfs3 image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@main
      - uses: sigstore/cosign-installer@main
      - uses: chainguard-dev/actions/apko-build@main
        id: apko
        with:
          tag: ghcr.io/${{ github.repository }}:latest
          archs: x86_64

      - uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # v1.13.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - shell: bash
        run: |
          # TODO: Add attributes based on things like the commit.
          COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.apko.outputs.digest }}